import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const IndexPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Skylight AI ✨ powered application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://dash.skylightai.io?utm_source=nextjs-template"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "} 
              <span
              
              style={
                {
                  fontWeight: "bold",
                  textDecoration: "none",
                }

              }>
              Skylight AI ✨
                </span>
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.thirteen}>
            <h1
              className={inter.className}
              style={{
                paddingLeft: "5px",
                fontSize: "80px",
              }}
            >
            ✨
            </h1>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="/ssr"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Pages (Next.js 12)<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              View an implementation of our payment gate with the pages
              directory.
            </p>
          </a>

          <a
            href="/app/ssr"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              App (Next.js 13) <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              View an implementation of our payment gate with the app directory.
            </p>
          </a>

          <a
            href="https://github.com/yannikouloumbis"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Documentation <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Explore the full capability of Skylight&apos;s API (Powered by Whop).
            </p>
          </a>

          <a
            href="windowai.io"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Discord <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Join our Window AI Devs Discord community for on-demand support.
            </p>
          </a>
        </div>
      </main>
    </>
  );
};

export default IndexPage;
